name: flutter_ringtone_player
description: A simple player for system default ringtones, alarms and notifications
version: 3.2.0
homepage: https://github.com/inway/flutter_ringtone_player
repository: https://github.com/inway/flutter_ringtone_player

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.9

dev_dependencies:
  test: ^1.16.8
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.inway.ringtone.player
        pluginClass: FlutterRingtonePlayerPlugin
      ios:
        pluginClass: FlutterRingtonePlayerPlugin
